version: 2

jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --path=vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rspec --format documentation --color 
